export const REGISTER_EMPLOYEE = "REGISTER_EMPLOYEE";
export const FETCH_ALL_EMPLOYEES = "FETCH_ALL_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
